<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SUNILs-MacBook-Pro.local" failures="1" tests="7" name="GreatLearning.DemoTest.Registration" time="16.086" errors="0" timestamp="20 Feb 2022 05:04:17 GMT" skipped="0">
  <testcase classname="GreatLearning.DemoTest.Registration" name="LaunchingApplication" time="6.659"/>
  <testcase classname="GreatLearning.DemoTest.Registration" name="verifyingBasicInformationPageAndEnteringData" time="1.484">
    <failure message="test failed expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: test failed expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at GreatLearning.DemoTest.Registration.verifyingBasicInformationPageAndEnteringData(Registration.java:65)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyingBasicInformationPageAndEnteringData -->
  <testcase classname="GreatLearning.DemoTest.Registration" name="verifyingProfessionalDetailsPageAndEnteringData" time="0.986"/>
  <testcase classname="GreatLearning.DemoTest.Registration" name="verifyingUerProgrammingExperiancePageAndEnteringData" time="1.486"/>
  <testcase classname="GreatLearning.DemoTest.Registration" name="verifyingUserEducationPageAndEnteringData" time="0.908"/>
  <testcase classname="GreatLearning.DemoTest.Registration" name="verifyingLinkedinProfileEnterTextAndEnteringData" time="1.981"/>
  <testcase classname="GreatLearning.DemoTest.Registration" name="verifyingLFinalSubmission" time="2.582"/>
</testsuite> <!-- GreatLearning.DemoTest.Registration -->
